name: Run Threat Generator

on:
  workflow_dispatch:  # <-- Lets you run it manually
  schedule:
    - cron: '*/5 * * * *'  # <-- Runs every 5 minutes

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11' 

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Data Generator
        # Set environment variables from GitHub Secrets
        env:
          DB_PASS: ${{ secrets.db_pass }}
          DB_USER: ${{ secrets.db_user }}
          DB_HOST: ${{ secrets.db_host }}
          DB_NAME: ${{ secrets.db_name }}
          DB_PORT: ${{ secrets.db_port }}
        run: |
          python data_generator.py
